spring:
  config:
    import: application-common.yml
  datasource:
    url: jdbc:oracle:thin:@adbspringboot_high?TNS_ADMIN=/root/app/wallet  
  profiles:
    active: oci
oci:
  tenant:
    region: sa-santiago-1
    vault:
      db-password-ocid: ocid1.vaultsecret.oc1.sa-santiago-1.amaaaaaavoaa5zia5hv3trplptrplbqcebz4flecehtjlym7v4gmouemuqha
      db-username-ocid: ocid1.vaultsecret.oc1.sa-santiago-1.amaaaaaavoaa5ziajtnbric5kxm6nbx266kjiccghdftgxp246kvia7f2r7q