spring:
  config:
    import: application-common.yml
  datasource:
    url: jdbc:oracle:thin:@helloatp_high?TNS_ADMIN=/Wallet_helloATP
oci:
  tenant:
    region: eu-frankfurt-1
    vault:
      db-password-ocid: ocid1.vaultsecret.oc1.eu-frankfurt-1.amaaaaaa7bs7v7iayxkjahpfsmx4dsn7ukzhcko7s6w2k5sxu3ivtpn3hsoq
      db-username-ocid: ocid1.vaultsecret.oc1.eu-frankfurt-1.amaaaaaa7bs7v7iayswnoynwvozw6dejmn66o4w4iluv5gq3jmhenhcqcrja